version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - ".:/mnt/host/"
  frontend:
    build: ./src/webinterface/clean-frontend/
    ports:
      - "8080:8080"
    depends_on: 
      - "backend"
